pipeline {
    agent {
        docker {
            image 'node'
            args '-p 3003:3003'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'sudo ./jenkins/scripts/build.sh'
            }
        }
        stage('Test') {
            steps {
                sh 'sudo ./jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh 'sudo ./jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh 'sudo ./jenkins/scripts/kill.sh'
            }
        }
    }
}
